---
- hosts: localhost
  tasks:
    - name: download nexus artifact
      maven_artifact:
        group_id: oi
        version: latest
        extension: jar
        artifact_id: lbs_ds_sender
        repository_url: http://http://63.32.43.9:8081/repository/work-maven-repo/
        username: admin
        password: admin
        dest: /tmp/



- hosts: aws_ec2 
  become: True
  tasks:
    - name: copy jar to target
      copy:
        src: /tmp/exhibit.jar
        dest: /var/www/
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
    - name: Start Apache 
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
